altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  66970eed-6b45-40a1-9f13-928d3429d58d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-24T11:27:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: eadb0be8-7111-4403-b92e-32c59982d4f3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 758a2ef5-1fef-467a-8575-6925648f7347
        userCondition: null
fs: hardDiskImages
handle: products
name: Products
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
